name: grafana-mltp
volumes:
  grafana:
  mimir:
  tempo:
  loki:
services:

  # The Grafana dashboarding server.
  grafana:
    image: grafana/grafana:12.3.1
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch correlations traceQLStreaming metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # The Tempo service stores traces send to it by Grafana opentelemetry-collector, and takes
  # queries from Grafana to visualise those traces.
  tempo:
    image: grafana/tempo:2.8.1
    restart: unless-stopped
    expose:
      - 3200
      - 9411
      - 55680
      - 55681
      - 14250
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - tempo:/var/tempo
      - "./tempo/tempo.yaml:/etc/tempo.yaml"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # The Loki service stores logs sent to it, and takes queries from Grafana
  # to visualise those logs.
  loki:
    image: grafana/loki:3.5.1
    restart: unless-stopped
    command: ["--pattern-ingester.enabled=true", "-config.file=/etc/loki/loki.yaml"]
    expose:
      - 3100
    volumes:
      - loki:/loki
      - "./loki/loki.yaml:/etc/loki/loki.yaml"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  mimir:
    image: grafana/mimir:2.16.0
    restart: unless-stopped
    command: ["-ingester.native-histograms-ingestion-enabled=true", "-config.file=/etc/mimir.yaml"]
    expose:
      - 9009
    volumes:
      - mimir:/data
      - "./mimir/mimir.yaml:/etc/mimir.yaml"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"