name: grafana-mltp
volumes:
  grafana:
  mimir:
  tempo:
  loki:
services:
  # Grafana Alloy batches and processes traces sent to it, generating
  # auto-logs from those traces.
  # Includes Metrics, Logs, Traces and Profiles.
  alloy:
    image: grafana/alloy:v1.12.1
    restart: unless-stopped
    ports:
      - "12350:12350"
      - "12347:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
      - "4317:4317"
      - "4318:4318"
    environment:
      - OTELCOL_AUTH_BEARER_CREDS_TOKEN=${OTELCOL_AUTH_BEARER_CREDS_TOKEN}  
    volumes:
      - "./alloy/config.alloy:/etc/alloy/config.alloy"
      - "./alloy/endpoints.json:/etc/alloy/endpoints.json"
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=experimental",
      "/etc/alloy/config.alloy",
    ]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
  # The Grafana dashboarding server.
  grafana:
    image: grafana/grafana:12.3.1
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
  # The Tempo service stores traces send to it by Grafana Alloy, and takes
  # queries from Grafana to visualise those traces.
  tempo:
    image: grafana/tempo:2.8.1
    restart: unless-stopped
    expose:
      - 3200
      - 9411
      - 55680
      - 55681
      - 14250
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - tempo:/var/tempo
      - "./tempo/tempo.yaml:/etc/tempo.yaml"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # The Loki service stores logs sent to it, and takes queries from Grafana
  # to visualise those logs.
  loki:
    image: grafana/loki:3.5.1
    restart: unless-stopped
    command: ["--pattern-ingester.enabled=true", "-config.file=/etc/loki/loki.yaml"]
    expose:
      - 3100
    volumes:
      - loki:/loki
      - "./loki/loki.yaml:/etc/loki/loki.yaml"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
  mimir:
    image: grafana/mimir:2.16.0
    restart: unless-stopped
    command: ["-ingester.native-histograms-ingestion-enabled=true", "-config.file=/etc/mimir.yaml"]
    expose:
      - 9009
    volumes:
      - mimir:/data
      - "./mimir/mimir.yaml:/etc/mimir.yaml"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
  nginx:
    image: nginx:1.29-alpine
    profiles:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-grafana.conf.template:/etc/nginx/templates/nginx-grafana.conf.template:ro
      - ./nginx/nginx-alloy.conf.template:/etc/nginx/templates/nginx-alloy.conf.template:ro
      - ./nginx/nginx-main.conf:/etc/nginx/nginx.conf:ro
    environment:
      # Pass the environment variable to the container
      - OTLP_DOMAIN=${OTLP_DOMAIN}
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    depends_on:
      - grafana
      - alloy