apiVersion: 1

groups:
  - orgId: 1
    name: "springboot错误日志"
    folder: "Spring Boot"
    interval: 1m
    rules:
      - uid: "spring_log_error_warn"
        title: "服务异常日志告警"
        condition: C

        data:
          - refId: A
            datasourceUid: "loki"
            relativeTimeRange:
              from: 300
              to: 0
            model:
              refId: A
              editorMode: code
              queryType: range
              expr: |
                sum by (service_name, severity_text, exception_message, exception_type) (
                  count_over_time(
                    {severity_text=~"ERROR|WARN"}
                    | exception_type=~".+"
                    [5m]
                  )
                )
              maxDataPoints: 43200
              intervalMs: 1000

          - refId: B
            datasourceUid: "__expr__"
            model:
              refId: B
              type: reduce
              expression: A
              reducer: last
              # 有些版本还需要 settings
              settings:
                mode: dropNN

          - refId: C
            datasourceUid: "__expr__"
            model:
              refId: C
              type: threshold
              expression: B
              conditions:
                - type: query
                  query:
                    params: [B]
                  reducer:
                    type: last
                  evaluator:
                    type: gt
                    params: [0]
                  operator:
                    type: and

        for: 1m

        annotations:
          summary: "服务 {{ $labels.service_name }} 检测到 {{ $labels.severity_text }}（近5分钟）"
          description: |
            服务名称: {{ $labels.service_name }}
            日志级别: {{ $labels.severity_text }}
            异常类型: {{ $labels.exception_type }}
            错误信息: {{ $labels.exception_message }}
            计数(最近值): {{ $values.B }}

        labels:
          severity: "警告"
