apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          # 兼容：trace_id=xxx、traceId=xxx、"trace_id":"xxx"
          matcherRegex: '.*(?:trace[_]?id)["=:\s]*"?([0-9a-fA-F]{16,32})"?.*'
          name: traceId
          url: '$${__value.raw}'

  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://tempo:3200
    jsonData:
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: 'Mimir'
      tracesToLogs:
        datasourceUid: loki
        filterByTraceID: true
        spanEndTimeShift: "500ms"
        spanStartTimeShift: "-500ms"
        tags: ['beast']

  - name: Mimir
    type: prometheus
    access: proxy
    uid: mimir
    url: http://mimir:9009/prometheus
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
      httpMethod: POST
      timeInterval: "2s"
